/*
 * SimulationResultsWindow.java
 *
 */

package jrs.analyzer;

import java.text.*;
import java.util.*;
import javax.swing.tree.*;
import jrs.*;

/** A window to display the results of the simulation generated by the 
  * RankingServiceAnalyzer tool.
  *
  * @author Derek Hilder
  */
public class SimulationResultsWindow extends javax.swing.JDialog {
    
    SimulationReport report;
    
    /** Creates new form SimulationResultsWindow
      * 
      * @param parent
      * @param report 
      *     The simulation report generated by the RankingServiceAnalyzer class. 
      */
    public SimulationResultsWindow(java.awt.Frame parent, SimulationReport report) {
        
        super(parent, false);
        
        initComponents();
        
        this.report = report;
        resultsTree.setModel(report);
        
        if (!(report.getRankingService() instanceof TimerBasedRankingService)) {
            pauseButton.setVisible(false);
            resumeButton.setVisible(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTree = new javax.swing.JTree();
        resumeButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jScrollPane1.setViewportView(resultsTree);

        resumeButton.setText("Resume");
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(pauseButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(resumeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pauseButton)
                    .add(resumeButton))
                .add(17, 17, 17))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        if (report.getRankingService() instanceof TimerBasedRankingService) {
            ((TimerBasedRankingService)report.getRankingService()).resumeUpdating();
        }
    }//GEN-LAST:event_resumeButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if (report.getRankingService() instanceof TimerBasedRankingService) {
            ((TimerBasedRankingService)report.getRankingService()).pauseUpdating();
        }
    }//GEN-LAST:event_pauseButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JTree resultsTree;
    private javax.swing.JButton resumeButton;
    // End of variables declaration//GEN-END:variables
    
}
